# Site settings
title: Lotek Media
email: me@johnmann.org
description: This is my personal github site that I have random code snippets, sandboxes, and some random thoughts.  Thanks for stopping by.  Check out my blog at <a href="http://johnmann.org">http://johnmann.org</>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lotekmedia.github.io" # the base hostname & protocol for your site
twitter_username: lotekmedia
github_username:  lotekmedia
default_bg:       default_bg.jpg
search:           true
share:            true
readtime:         true
animated_fins:    true
fin_color:        "255,255,255"
# Build settings
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

owner:
  name:           John Mann
  avatar:         me-beach.jpg
  email:          john@lotekmedia.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    A code monkey with a love for teaching.
  # Social networking links used in footer. Update and remove as you like.
  twitter: http://twitter.com/lotekmedia
  facebook: http://facebook.com/ComputerJohn
  github: http://lotekmedia.github.io
  linkedin: http://linkedin.com/in/jmmann

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Blog
    external: true
    url: http://johnmann.org

collections:  
 - people
